/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : string,
  'records' : Array<MemberAttendance>,
  'date' : string,
  'totalAbsent' : bigint,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'sectionId' : string,
  'totalPresent' : bigint,
}
export interface Book {
  'id' : string,
  'sentences' : Array<Sentence>,
  'title' : string,
  'topic' : [] | [string],
  'createdAt' : bigint,
  'type' : string,
  'level' : string,
  'author' : string,
  'updatedAt' : bigint,
}
export interface ExpenseEntry { 'description' : string, 'amount' : bigint }
export interface FinancialReport {
  'id' : string,
  'offerings' : bigint,
  'date' : string,
  'fundraising' : bigint,
  'expenses' : Array<ExpenseEntry>,
  'createdAt' : bigint,
  'vows' : Array<VowEntry>,
  'totalIncome' : bigint,
  'groupFinancialEntries' : Array<LinkedGroupFinancialEntry>,
  'sales' : bigint,
  'totalExpenses' : bigint,
  'updatedAt' : bigint,
  'sectionId' : string,
  'otherIncome' : Array<OtherIncomeEntry>,
  'endingBalance' : bigint,
  'startingBalance' : bigint,
}
export interface Group {
  'id' : string,
  'treasurerId' : string,
  'name' : string,
  'createdAt' : bigint,
  'presidentId' : string,
  'updatedAt' : bigint,
  'sectionId' : string,
  'memberIds' : Array<string>,
  'secretaryId' : string,
}
export interface GroupFinancialReport {
  'id' : string,
  'expense' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'deposit' : bigint,
  'updatedAt' : bigint,
  'groupId' : string,
  'sectionId' : string,
}
export interface LinkedGroupFinancialEntry {
  'transactionType' : TransactionType,
  'originatingGroupName' : string,
  'date' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'groupTransactionId' : string,
  'amount' : bigint,
}
export interface Member {
  'id' : string,
  'sex' : string,
  'dateOfBirth' : string,
  'createdAt' : bigint,
  'profession' : string,
  'fullName' : string,
  'updatedAt' : bigint,
  'sectionId' : string,
  'address' : string,
  'phone' : string,
  'mother' : string,
  'father' : string,
}
export interface MemberAttendance {
  'status' : string,
  'memberId' : string,
  'absenceReason' : [] | [string],
}
export interface MonthlyRemark {
  'remark' : string,
  'month' : bigint,
  'year' : bigint,
  'updatedAt' : bigint,
  'sectionId' : string,
}
export interface OtherIncomeEntry { 'amount' : bigint, 'reason' : string }
export interface Program {
  'id' : string,
  'preacher' : string,
  'meetingLeader' : string,
  'date' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'sectionId' : string,
  'devotionLeader' : string,
  'songLeader' : string,
}
export interface SectionCommittee {
  'treasurerId' : [] | [string],
  'presidentId' : [] | [string],
  'updatedAt' : bigint,
  'sectionId' : string,
  'secretaryId' : [] | [string],
}
export interface Sentence {
  'id' : string,
  'grammaticHints' : [] | [string],
  'createdAt' : bigint,
  'chinese' : string,
  'updatedAt' : bigint,
  'pinyin' : string,
  'english' : string,
}
export type TransactionType = { 'expense' : null } |
  { 'deposit' : null };
export interface UserProfile {
  'committeeRole' : [] | [string],
  'name' : string,
  'section' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VowEntry { 'memberIds' : Array<string>, 'amount' : bigint }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSentenceToBook' : ActorMethod<[string, Sentence], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAttendanceRecord' : ActorMethod<[AttendanceRecord], string>,
  'createBook' : ActorMethod<[Book], string>,
  'createFinancialReport' : ActorMethod<[FinancialReport], string>,
  'createGroup' : ActorMethod<[Group], string>,
  'createGroupFinancialReport' : ActorMethod<[GroupFinancialReport], string>,
  'createMember' : ActorMethod<[Member], string>,
  'createProgram' : ActorMethod<[Program], string>,
  'deleteAttendanceRecord' : ActorMethod<[string], undefined>,
  'deleteBook' : ActorMethod<[string], undefined>,
  'deleteFinancialReport' : ActorMethod<[string], undefined>,
  'deleteGroup' : ActorMethod<[string], undefined>,
  'deleteGroupFinancialReport' : ActorMethod<[string], undefined>,
  'deleteMember' : ActorMethod<[string], undefined>,
  'deleteProgram' : ActorMethod<[string], undefined>,
  'deleteSentenceFromBook' : ActorMethod<[string, string], undefined>,
  'getAttendanceRecord' : ActorMethod<[string], [] | [AttendanceRecord]>,
  'getBook' : ActorMethod<[string], [] | [Book]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFinancialReport' : ActorMethod<[string], [] | [FinancialReport]>,
  'getGroup' : ActorMethod<[string], [] | [Group]>,
  'getGroupFinancialReport' : ActorMethod<
    [string],
    [] | [GroupFinancialReport]
  >,
  'getLastSyncTime' : ActorMethod<[], bigint>,
  'getMember' : ActorMethod<[string], [] | [Member]>,
  'getMonthlyRemark' : ActorMethod<
    [string, bigint, bigint],
    [] | [MonthlyRemark]
  >,
  'getProgram' : ActorMethod<[string], [] | [Program]>,
  'getSectionCommittee' : ActorMethod<[string], [] | [SectionCommittee]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeCommitteeCredentials' : ActorMethod<[Array<Principal>], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAttendanceRecords' : ActorMethod<[string], Array<AttendanceRecord>>,
  'listBooks' : ActorMethod<[], Array<Book>>,
  'listFinancialReports' : ActorMethod<[string], Array<FinancialReport>>,
  'listGroupFinancialReports' : ActorMethod<
    [string],
    Array<GroupFinancialReport>
  >,
  'listGroups' : ActorMethod<[string], Array<Group>>,
  'listMembers' : ActorMethod<[string], Array<Member>>,
  'listPrograms' : ActorMethod<[string], Array<Program>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMonthlyRemark' : ActorMethod<[MonthlyRemark], undefined>,
  'updateAttendanceRecord' : ActorMethod<[AttendanceRecord], undefined>,
  'updateBook' : ActorMethod<[Book], undefined>,
  'updateFinancialReport' : ActorMethod<[FinancialReport], undefined>,
  'updateGroup' : ActorMethod<[Group], undefined>,
  'updateGroupFinancialReport' : ActorMethod<[GroupFinancialReport], undefined>,
  'updateMember' : ActorMethod<[Member], undefined>,
  'updateProgram' : ActorMethod<[Program], undefined>,
  'updateSectionCommittee' : ActorMethod<[SectionCommittee], undefined>,
  'updateSentenceInBook' : ActorMethod<[string, Sentence], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];