/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Sentence = IDL.Record({
  'id' : IDL.Text,
  'grammaticHints' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'chinese' : IDL.Text,
  'updatedAt' : IDL.Int,
  'pinyin' : IDL.Text,
  'english' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MemberAttendance = IDL.Record({
  'status' : IDL.Text,
  'memberId' : IDL.Text,
  'absenceReason' : IDL.Opt(IDL.Text),
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Text,
  'records' : IDL.Vec(MemberAttendance),
  'date' : IDL.Text,
  'totalAbsent' : IDL.Nat,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'sectionId' : IDL.Text,
  'totalPresent' : IDL.Nat,
});
export const Book = IDL.Record({
  'id' : IDL.Text,
  'sentences' : IDL.Vec(Sentence),
  'title' : IDL.Text,
  'topic' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'type' : IDL.Text,
  'level' : IDL.Text,
  'author' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const ExpenseEntry = IDL.Record({
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const VowEntry = IDL.Record({
  'memberIds' : IDL.Vec(IDL.Text),
  'amount' : IDL.Nat,
});
export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'deposit' : IDL.Null,
});
export const LinkedGroupFinancialEntry = IDL.Record({
  'transactionType' : TransactionType,
  'originatingGroupName' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'groupTransactionId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const OtherIncomeEntry = IDL.Record({
  'amount' : IDL.Nat,
  'reason' : IDL.Text,
});
export const FinancialReport = IDL.Record({
  'id' : IDL.Text,
  'offerings' : IDL.Nat,
  'date' : IDL.Text,
  'fundraising' : IDL.Nat,
  'expenses' : IDL.Vec(ExpenseEntry),
  'createdAt' : IDL.Int,
  'vows' : IDL.Vec(VowEntry),
  'totalIncome' : IDL.Nat,
  'groupFinancialEntries' : IDL.Vec(LinkedGroupFinancialEntry),
  'sales' : IDL.Nat,
  'totalExpenses' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'sectionId' : IDL.Text,
  'otherIncome' : IDL.Vec(OtherIncomeEntry),
  'endingBalance' : IDL.Int,
  'startingBalance' : IDL.Int,
});
export const Group = IDL.Record({
  'id' : IDL.Text,
  'treasurerId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'presidentId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'sectionId' : IDL.Text,
  'memberIds' : IDL.Vec(IDL.Text),
  'secretaryId' : IDL.Text,
});
export const GroupFinancialReport = IDL.Record({
  'id' : IDL.Text,
  'expense' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'deposit' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'groupId' : IDL.Text,
  'sectionId' : IDL.Text,
});
export const Member = IDL.Record({
  'id' : IDL.Text,
  'sex' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'createdAt' : IDL.Int,
  'profession' : IDL.Text,
  'fullName' : IDL.Text,
  'updatedAt' : IDL.Int,
  'sectionId' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'mother' : IDL.Text,
  'father' : IDL.Text,
});
export const Program = IDL.Record({
  'id' : IDL.Text,
  'preacher' : IDL.Text,
  'meetingLeader' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'sectionId' : IDL.Text,
  'devotionLeader' : IDL.Text,
  'songLeader' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'committeeRole' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'section' : IDL.Opt(IDL.Text),
});
export const MonthlyRemark = IDL.Record({
  'remark' : IDL.Text,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'sectionId' : IDL.Text,
});
export const SectionCommittee = IDL.Record({
  'treasurerId' : IDL.Opt(IDL.Text),
  'presidentId' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'sectionId' : IDL.Text,
  'secretaryId' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSentenceToBook' : IDL.Func([IDL.Text, Sentence], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAttendanceRecord' : IDL.Func([AttendanceRecord], [IDL.Text], []),
  'createBook' : IDL.Func([Book], [IDL.Text], []),
  'createFinancialReport' : IDL.Func([FinancialReport], [IDL.Text], []),
  'createGroup' : IDL.Func([Group], [IDL.Text], []),
  'createGroupFinancialReport' : IDL.Func(
      [GroupFinancialReport],
      [IDL.Text],
      [],
    ),
  'createMember' : IDL.Func([Member], [IDL.Text], []),
  'createProgram' : IDL.Func([Program], [IDL.Text], []),
  'deleteAttendanceRecord' : IDL.Func([IDL.Text], [], []),
  'deleteBook' : IDL.Func([IDL.Text], [], []),
  'deleteFinancialReport' : IDL.Func([IDL.Text], [], []),
  'deleteGroup' : IDL.Func([IDL.Text], [], []),
  'deleteGroupFinancialReport' : IDL.Func([IDL.Text], [], []),
  'deleteMember' : IDL.Func([IDL.Text], [], []),
  'deleteProgram' : IDL.Func([IDL.Text], [], []),
  'deleteSentenceFromBook' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAttendanceRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AttendanceRecord)],
      ['query'],
    ),
  'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFinancialReport' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FinancialReport)],
      ['query'],
    ),
  'getGroup' : IDL.Func([IDL.Text], [IDL.Opt(Group)], ['query']),
  'getGroupFinancialReport' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GroupFinancialReport)],
      ['query'],
    ),
  'getLastSyncTime' : IDL.Func([], [IDL.Int], ['query']),
  'getMember' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
  'getMonthlyRemark' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Opt(MonthlyRemark)],
      ['query'],
    ),
  'getProgram' : IDL.Func([IDL.Text], [IDL.Opt(Program)], ['query']),
  'getSectionCommittee' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SectionCommittee)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeCommitteeCredentials' : IDL.Func([IDL.Vec(IDL.Principal)], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAttendanceRecords' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'listBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'listFinancialReports' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FinancialReport)],
      ['query'],
    ),
  'listGroupFinancialReports' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GroupFinancialReport)],
      ['query'],
    ),
  'listGroups' : IDL.Func([IDL.Text], [IDL.Vec(Group)], ['query']),
  'listMembers' : IDL.Func([IDL.Text], [IDL.Vec(Member)], ['query']),
  'listPrograms' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMonthlyRemark' : IDL.Func([MonthlyRemark], [], []),
  'updateAttendanceRecord' : IDL.Func([AttendanceRecord], [], []),
  'updateBook' : IDL.Func([Book], [], []),
  'updateFinancialReport' : IDL.Func([FinancialReport], [], []),
  'updateGroup' : IDL.Func([Group], [], []),
  'updateGroupFinancialReport' : IDL.Func([GroupFinancialReport], [], []),
  'updateMember' : IDL.Func([Member], [], []),
  'updateProgram' : IDL.Func([Program], [], []),
  'updateSectionCommittee' : IDL.Func([SectionCommittee], [], []),
  'updateSentenceInBook' : IDL.Func([IDL.Text, Sentence], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Sentence = IDL.Record({
    'id' : IDL.Text,
    'grammaticHints' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'chinese' : IDL.Text,
    'updatedAt' : IDL.Int,
    'pinyin' : IDL.Text,
    'english' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MemberAttendance = IDL.Record({
    'status' : IDL.Text,
    'memberId' : IDL.Text,
    'absenceReason' : IDL.Opt(IDL.Text),
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Text,
    'records' : IDL.Vec(MemberAttendance),
    'date' : IDL.Text,
    'totalAbsent' : IDL.Nat,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'sectionId' : IDL.Text,
    'totalPresent' : IDL.Nat,
  });
  const Book = IDL.Record({
    'id' : IDL.Text,
    'sentences' : IDL.Vec(Sentence),
    'title' : IDL.Text,
    'topic' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'type' : IDL.Text,
    'level' : IDL.Text,
    'author' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const ExpenseEntry = IDL.Record({
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const VowEntry = IDL.Record({
    'memberIds' : IDL.Vec(IDL.Text),
    'amount' : IDL.Nat,
  });
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'deposit' : IDL.Null,
  });
  const LinkedGroupFinancialEntry = IDL.Record({
    'transactionType' : TransactionType,
    'originatingGroupName' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'groupTransactionId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const OtherIncomeEntry = IDL.Record({
    'amount' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const FinancialReport = IDL.Record({
    'id' : IDL.Text,
    'offerings' : IDL.Nat,
    'date' : IDL.Text,
    'fundraising' : IDL.Nat,
    'expenses' : IDL.Vec(ExpenseEntry),
    'createdAt' : IDL.Int,
    'vows' : IDL.Vec(VowEntry),
    'totalIncome' : IDL.Nat,
    'groupFinancialEntries' : IDL.Vec(LinkedGroupFinancialEntry),
    'sales' : IDL.Nat,
    'totalExpenses' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'sectionId' : IDL.Text,
    'otherIncome' : IDL.Vec(OtherIncomeEntry),
    'endingBalance' : IDL.Int,
    'startingBalance' : IDL.Int,
  });
  const Group = IDL.Record({
    'id' : IDL.Text,
    'treasurerId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'presidentId' : IDL.Text,
    'updatedAt' : IDL.Int,
    'sectionId' : IDL.Text,
    'memberIds' : IDL.Vec(IDL.Text),
    'secretaryId' : IDL.Text,
  });
  const GroupFinancialReport = IDL.Record({
    'id' : IDL.Text,
    'expense' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'deposit' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'groupId' : IDL.Text,
    'sectionId' : IDL.Text,
  });
  const Member = IDL.Record({
    'id' : IDL.Text,
    'sex' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'createdAt' : IDL.Int,
    'profession' : IDL.Text,
    'fullName' : IDL.Text,
    'updatedAt' : IDL.Int,
    'sectionId' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'mother' : IDL.Text,
    'father' : IDL.Text,
  });
  const Program = IDL.Record({
    'id' : IDL.Text,
    'preacher' : IDL.Text,
    'meetingLeader' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'sectionId' : IDL.Text,
    'devotionLeader' : IDL.Text,
    'songLeader' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'committeeRole' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'section' : IDL.Opt(IDL.Text),
  });
  const MonthlyRemark = IDL.Record({
    'remark' : IDL.Text,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'sectionId' : IDL.Text,
  });
  const SectionCommittee = IDL.Record({
    'treasurerId' : IDL.Opt(IDL.Text),
    'presidentId' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'sectionId' : IDL.Text,
    'secretaryId' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSentenceToBook' : IDL.Func([IDL.Text, Sentence], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAttendanceRecord' : IDL.Func([AttendanceRecord], [IDL.Text], []),
    'createBook' : IDL.Func([Book], [IDL.Text], []),
    'createFinancialReport' : IDL.Func([FinancialReport], [IDL.Text], []),
    'createGroup' : IDL.Func([Group], [IDL.Text], []),
    'createGroupFinancialReport' : IDL.Func(
        [GroupFinancialReport],
        [IDL.Text],
        [],
      ),
    'createMember' : IDL.Func([Member], [IDL.Text], []),
    'createProgram' : IDL.Func([Program], [IDL.Text], []),
    'deleteAttendanceRecord' : IDL.Func([IDL.Text], [], []),
    'deleteBook' : IDL.Func([IDL.Text], [], []),
    'deleteFinancialReport' : IDL.Func([IDL.Text], [], []),
    'deleteGroup' : IDL.Func([IDL.Text], [], []),
    'deleteGroupFinancialReport' : IDL.Func([IDL.Text], [], []),
    'deleteMember' : IDL.Func([IDL.Text], [], []),
    'deleteProgram' : IDL.Func([IDL.Text], [], []),
    'deleteSentenceFromBook' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAttendanceRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AttendanceRecord)],
        ['query'],
      ),
    'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFinancialReport' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FinancialReport)],
        ['query'],
      ),
    'getGroup' : IDL.Func([IDL.Text], [IDL.Opt(Group)], ['query']),
    'getGroupFinancialReport' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GroupFinancialReport)],
        ['query'],
      ),
    'getLastSyncTime' : IDL.Func([], [IDL.Int], ['query']),
    'getMember' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
    'getMonthlyRemark' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Opt(MonthlyRemark)],
        ['query'],
      ),
    'getProgram' : IDL.Func([IDL.Text], [IDL.Opt(Program)], ['query']),
    'getSectionCommittee' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SectionCommittee)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeCommitteeCredentials' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAttendanceRecords' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'listBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'listFinancialReports' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FinancialReport)],
        ['query'],
      ),
    'listGroupFinancialReports' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GroupFinancialReport)],
        ['query'],
      ),
    'listGroups' : IDL.Func([IDL.Text], [IDL.Vec(Group)], ['query']),
    'listMembers' : IDL.Func([IDL.Text], [IDL.Vec(Member)], ['query']),
    'listPrograms' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMonthlyRemark' : IDL.Func([MonthlyRemark], [], []),
    'updateAttendanceRecord' : IDL.Func([AttendanceRecord], [], []),
    'updateBook' : IDL.Func([Book], [], []),
    'updateFinancialReport' : IDL.Func([FinancialReport], [], []),
    'updateGroup' : IDL.Func([Group], [], []),
    'updateGroupFinancialReport' : IDL.Func([GroupFinancialReport], [], []),
    'updateMember' : IDL.Func([Member], [], []),
    'updateProgram' : IDL.Func([Program], [], []),
    'updateSectionCommittee' : IDL.Func([SectionCommittee], [], []),
    'updateSentenceInBook' : IDL.Func([IDL.Text, Sentence], [], []),
  });
};

export const init = ({ IDL }) => { return []; };